version: 0.2

        
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing serverless CLI
      - npm install -g serverless
      - echo Installing npm dependencies of notes service
      - npm i
  build:
    on-failure: ABORT
    commands:
      - echo Deploying Resources
      - serverless deploy --stage dev --aws-profile serverlessApp

artifacts:
  files:
    - my-artifact/*
  name: MyProjectArtifacts
cache:
  paths:
    - 'node_modules/**/*'
